### PR TITLE
Add PR description template

### PR DESCRIPTION
**Pull request by shaoyuchu**
## Feature Description
A template of PR description. The template is expected to automatically pop up in order to guide users to provide useful information in their PR description.

## Root Cause
I'm creating a PR to generate some descriptive screenshots for the Git/Github tutorial. Instead of pushing some meaningless changes, I've decided to create a PR description template in response to @liangnaiyun-tw and @skychocowhite 's suggestion.

## Solution
The template contains 5 sections: "Feature/Bug Description", "Root cause", "Solution", "Related Resource", and "Result". Brief descriptions are also added in the template.

## Related Resource
* Issue #11 
* Reference: https://www.gitkraken.com/blog/enhancing-pull-request-descriptions-templates

### CODE REVIEW

**Comment by skychocowhite** [comment]
The template seems good, but should we change the title names?
For the title `Issue Description`, it seems like the pull request is fixing some problems or bugs for me, not so related to add new functionality.

**Comment by shaoyuchu** [comment]
> The template seems good, but should we change the title names? For the title `Issue Description`, it seems like the pull request is fixing some problems or bugs for me, not so related to add new functionality.

Sure, this problem is also bothering me. How about `Feature/Bug Description`?

**Comment by skychocowhite** [comment]
Maybe this is the better solution right now.
Since we can add labels for each issue and pull request, if time permits, maybe we can try to figure out how to use separate templates with different kinds of tags someday.

**Review by skychocowhite — APPROVED** [review]

**Review by liangnaiyun-tw — APPROVED** [review]
Let's try it

**Review by container513 — APPROVED** [review]

**Pull request merged**
